#ifndef DELICIOUS_BUILD_SETTINGS_H
#define DELICIOUS_BUILD_SETTINGS_H

//Main version declaration
#define ENG_VER_MAJOR 0
#define ENG_VER_MINOR 1
#define ENG_VER_PATCH 1

#define ENGINE_GL_MAJOR 4
#define ENGINE_GL_MINOR 4
#define DEFAULT_GLSL_VERSION 440

#define MAX_ENTITIES 786

#define USE_MEMORY_LIMIT 0
#define MEMORY_LIMIT 1024 * 1024 * 1024 // 1 GB

#define CON_MAX_NAME 32

#define USE_SCRIPTING 0

#endif