#ifndef DELICIOUS_BUILD_INFO_H
#define DELICIOUS_BUILD_INFO_H

#define ENGINE_VERSION	011
#define ENGINE_VERSION_MAJOR 0
#define ENGINE_VERSION_MINOR 1
#define ENGINE_VERSION_REVISION 1
#define ENGINE_VERSION_STRING "0.1.1"

#define ENGINE_GL_MAJOR 4
#define ENGINE_GL_MINOR 3

#endif