#ifndef DELICIOUS_BUILD_INFO_H
#define DELICIOUS_BUILD_INFO_H

#define ENGINE_VERSION	005
#define ENGINE_VERSION_MAJOR 0
#define ENGINE_VERSION_MINOR 0
#define ENGINE_VERSION_REVISION 5
#define ENGINE_VERSION_STRING "0.0.5"

#define ENGINE_GL_MAJOR 4
#define ENGINE_GL_MINOR 3

#define EXPOSE_GLOBAL_SYSTEM true

#endif